# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
ci:
  autoupdate_schedule: quarterly
  skip:
    - export-docs-env
    - export-ci-env
    - export-examples-env
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: local
    hooks:
      - id: export-docs-env
        name: export docs_env.yaml from pixi
        entry: |-
          bash -c "
            pixi workspace export conda-environment -e doc -n pablo-docs       \
            | rg -v '^  - -e \.$'                                              \
            | rg -U '\A((:?.|\n)*?)(- pip:)?\n+\z' --replace '$1'              \
            > devtools/conda-envs/docs_env.yaml                                \
            && git ls-files --error-unmatch devtools/conda-envs/docs_env.yaml
          "
        language: conda
        additional_dependencies:
          - pixi>=0.59.0
          - ripgrep>=15
          - git
          - bash
        files: "pixi.toml|pixi.lock|devtools/conda-envs/docs_env.yaml"
        pass_filenames: false
      - id: export-ci-env
        name: export test_env.yaml from pixi
        entry: |-
          bash -c "
            pixi workspace export conda-environment -e ci -n pablo-tests       \
            | rg -v '^  - -e \.$'                                              \
            | rg -U '\A((:?.|\n)*?)(- pip:)?\n+\z' --replace '$1'              \
            > devtools/conda-envs/test_env.yaml                                \
            && git ls-files --error-unmatch devtools/conda-envs/test_env.yaml
          "
        language: conda
        additional_dependencies:
          - pixi>=0.59.0
          - ripgrep>=15
          - git
          - bash
        files: "pixi.toml|pixi.lock|devtools/conda-envs/test_env.yaml"
        pass_filenames: false
      - id: export-examples-env
        name: export examples_env.yaml from pixi
        entry: |-
          bash -c "
            pixi workspace export conda-environment -e example -n pablo-examples  \
            | rg -v '^  - -e \.$'                                                 \
            | rg -U '\A((:?.|\n)*?)(- pip:)?\n+\z' --replace '$1'                 \
            > devtools/conda-envs/examples_env.yaml                               \
            && git ls-files --error-unmatch devtools/conda-envs/examples_env.yaml
          "
        language: conda
        additional_dependencies:
          - pixi>=0.59.0
          - ripgrep>=15
          - git
          - bash
        files: "pixi.toml|pixi.lock|devtools/conda-envs/examples_env.yaml"
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.pdb'
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma
        files: "openff"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.9
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
        files: "openff"
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.7.0
  #   hooks:
  #     - id: interrogate
  #       args: ["openff/pablo/", "-e", "openff/pablo/_tests/"]
  #       pass_filenames: false
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        files: ^examples
