[build-system]
requires = [
  "setuptools >= 77.0.3",
  "versioningit",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "openff-pablo"
description = "New, independent implementation of `Topology.from_pdb`"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Josh Mitchell", email = "josh.mitchell@openforcefield.org" },
]
maintainers = [
  { name = "Josh Mitchell", email = "josh.mitchell@openforcefield.org" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]
keywords = [
  "molecular mechanics",
]
dynamic = [
  "version",
]

[project.optional-dependencies]
test = [
  "pytest>=6.0",
  "pytest-xdist>=2.5",
  "pytest-cov>=3.0",
]
doc = [
  "sphinx",
]

# [project.urls]
# source = "https://github.com/openforcefield/openff-pablo"
# documentation = "https://openff-pablo.readthedocs.io"

[tool.versioningit]
default-version = "v0.0.0.dev0+VERSIONMISSING"
format.dirty = "{base_version}"
format.distance-dirty = "{base_version}.post{distance}+{vcs}{rev}"

[tool.pytest.ini_options]
minversion = "6.0"
timeout = 120
log_format = "%(asctime)s.%(msecs)03d [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
  "openff/pablo/_tests",
]
markers = [
  "slow: mark the test to be skippable when fast results are needed", #  deselect with `-m "not slow"`
]

[tool.setuptools.packages.find]
include = ["openff.*"]

[tool.pyright]
include = ["openff"]
exclude = [
  ".soap",
  ".pixi",
  "**/node_modules",
  "**/__pycache__",
]
"ignore" = [
  "docs",
  "examples",
  "**/_tests/data",
  "**/.*",
]

typeCheckingMode = "strict"
strictGenericNarrowing = true

reportUnsupportedDunderAll = "error"
reportUnknownVariableType = "warning"
reportUnknownParameterType = "error"
reportUnknownArgumentType = "warning"
reportUnknownLambdaType = "warning"
reportUnknownMemberType = "warning"
reportAny = "information"
reportMissingTypeStubs = "none"
reportUnnecessaryIsInstance = "none"
reportUnnecessaryTypeIgnoreComment = "error"
reportPrivateUsage = "none"
reportMissingTypeArgument = "none"
reportIgnoreCommentWithoutRule = "error"
reportUnnecessaryComparison = "information"

[tool.ruff]
namespace-packages = ["openff/pablo/"]

[tool.ruff.lint]
ignore = ["E731"]

[tool.ruff.lint.isort]
known-third-party = ["openff.toolkit", "openff.utilities", "openff.units"]
known-first-party = ["openff.pablo"]
